name: custom_progress_bar
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/Boburbek6010/custom_progress_bar

environment:
  sdk: '>=3.7.2 <4.0.0'
  flutter: '>=3.29.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

